# Generated by Django 4.1.3 on 2023-01-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='placement_officer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('institute_name', models.CharField(max_length=50)),
                ('institute_code', models.IntegerField()),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='recuiter_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=40)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('institute_name', models.CharField(max_length=50)),
                ('institute_code', models.IntegerField()),
                ('student_uid', models.IntegerField()),
                ('degree', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=30)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='general',
        ),
    ]
