# Generated by Django 4.1.2 on 2023-02-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_table',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=40, unique=True)),
                ('comment', models.TextField()),
                ('jobpost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.jobpost_table')),
            ],
        ),
    ]
