# Generated by Django 4.1.2 on 2023-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_comment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_table',
            name='user_email',
            field=models.CharField(max_length=40),
        ),
    ]
