# Generated by Django 4.1.3 on 2023-01-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_placement_officer_table_recuiter_table_student_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement_officer_table',
            name='institute_code',
        ),
        migrations.RemoveField(
            model_name='placement_officer_table',
            name='institute_name',
        ),
        migrations.RemoveField(
            model_name='student_table',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student_table',
            name='institute_code',
        ),
        migrations.RemoveField(
            model_name='student_table',
            name='institute_name',
        ),
        migrations.RemoveField(
            model_name='student_table',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='student_table',
            name='student_uid',
        ),
        migrations.AlterField(
            model_name='recuiter_table',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
