# Generated by Django 4.1.2 on 2023-03-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_alter_comment_table_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost_table',
            name='recruiter_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='app_backend.recuiter_table'),
        ),
    ]
