# Generated by Django 4.1.3 on 2023-02-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_remove_placement_officer_table_institute_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement_officer_table',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recuiter_table',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='placement_officer_table',
            name='email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recuiter_table',
            name='email',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_table',
            name='email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
