# Generated by Django 4.1.2 on 2023-02-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_remove_placement_officer_table_institute_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobpost_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('recruiter_name', models.CharField(max_length=40)),
                ('job_position', models.CharField(max_length=30)),
                ('job_description', models.TextField()),
            ],
        ),
    ]
