# Generated by Django 4.1.2 on 2023-02-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_jobpost_table'),
        ('app_backend', '0004_remove_placement_officer_table_id_and_more'),
    ]

    operations = [
    ]
