# Generated by Django 4.1.2 on 2023-03-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_jobpost_table_recruiter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost_table',
            name='recruiter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.recuiter_table'),
        ),
    ]
