# Generated by Django 4.1.2 on 2023-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_alter_jobpost_table_recruiter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost_table',
            name='recruiter_id',
        ),
        migrations.AddField(
            model_name='jobpost_table',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
